services:
  shufflr:
    image: ghcr.io/justin-arnold/shufflr:latest
    platform: linux/amd64 
    ports:
      - "${SHUFFLR_PORT:-8080}:${SHUFFLR_PORT:-8080}"
    environment:
      - PORT=${SHUFFLR_PORT:-8080}
      - DATABASE_PATH=${SHUFFLR_DATABASE_PATH:-/app/data/shufflr.db}
      - UPLOAD_DIR=${SHUFFLR_UPLOAD_DIR:-/app/data/uploads}
      - BASE_URL=${SHUFFLR_BASE_URL:-http://localhost:8080}
      - SESSION_SECRET=${SHUFFLR_SESSION_SECRET}
    volumes:
      # Persist database and uploaded images
      - shufflr_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shufflr_network

volumes:
  shufflr_data:
    driver: local

networks:
  shufflr_network:
    driver: bridge