services:
  shufflr:
    image: ghcr.io/justin-arnold/shufflr:latest
    platform: linux/amd64 
    ports:
      - "${SHUFFLR_PORT:-8080}:${SHUFFLR_PORT:-8080}"
    environment:
      - PORT=${SHUFFLR_PORT:-8080}
      - DATABASE_PATH=${SHUFFLR_DATABASE_PATH:-/app/data/shufflr.db}
      - UPLOAD_DIR=${SHUFFLR_UPLOAD_DIR:-/app/data/uploads}
      - BASE_URL=${SHUFFLR_BASE_URL:-http://localhost:8080}
      - SESSION_SECRET=${SHUFFLR_SESSION_SECRET}
    volumes:
      # Mount host directories for direct access to data
      - ${SHUFFLR_DATA_DIR:-./shufflr-data}:/app/data
      # Alternative: separate mounts for more granular control
      # - ${SHUFFLR_DATABASE_DIR:-./shufflr-data}:/app/data
      # - ${SHUFFLR_UPLOAD_DIR_HOST:-./shufflr-data/uploads}:/app/data/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shufflr_network

# Remove the named volume since we're using bind mounts now
# volumes:
#   shufflr_data:
#     driver: local

networks:
  shufflr_network:
    driver: bridge